# Generated by Django 5.2.9 on 2025-12-25 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Название роли")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Роль",
                "verbose_name_plural": "Роли",
            },
        ),
        migrations.CreateModel(
            name="AccessRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("read_permission", models.BooleanField(default=False, verbose_name="Чтение своих")),
                ("read_all_permission", models.BooleanField(default=False, verbose_name="Чтение всех")),
                ("create_permission", models.BooleanField(default=False, verbose_name="Создание")),
                ("update_permission", models.BooleanField(default=False, verbose_name="Обновление своих")),
                ("update_all_permission", models.BooleanField(default=False, verbose_name="Обновление всех")),
                ("delete_permission", models.BooleanField(default=False, verbose_name="Удаление своих")),
                ("delete_all_permission", models.BooleanField(default=False, verbose_name="Удаление всех")),
                (
                    "element",
                    models.ForeignKey(
                        help_text="Модель, к которой применимо правило доступа",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Элемент правила доступа",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_rules",
                        to="roles.role",
                        verbose_name="Роль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Правило доступа",
                "verbose_name_plural": "Правила доступа",
                "constraints": [models.UniqueConstraint(fields=("element", "role"), name="unique_role_for_element")],
            },
        ),
    ]
