# Generated by Django 5.2.9 on 2025-12-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="Администратор"),
        ),
    ]
